services:
    _defaults:
        public: true

    coreshop.menu.renderer.json:
        alias: CoreShop\Bundle\MenuBundle\Renderer\JsonRenderer
        deprecated: { package: "coreshop/menu-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Bundle\MenuBundle\Renderer\JsonRenderer instead' }

